In [2]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
import matplotlib.pyplot as plt
import scipy
from scipy import stats

# NUMPY

In [14]:
a = np.array([1,2,2,2,3,4,5,9,10])

## MEAN

In [17]:
np.mean(a)

4.222222222222222

## MEDIAN

In [19]:
np.median(a)

3.0

## MODE

In [16]:
stats.mode(a,keepdims=False)

ModeResult(mode=2, count=3)

## VARIANCE

In [20]:
np.var(a)

9.28395061728395

## STANDARD DEVIATION

In [21]:
np.std(a)

3.0469576001782417

# 3D array

#### ZEROS

In [2]:
a = np.zeros([3,3,3])
a

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

#### ONES

In [3]:
b = np.ones([3,3,3])
b

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

### full->all values

In [4]:
c = np.full([3,3,3],8)
c

array([[[8, 8, 8],
        [8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8],
        [8, 8, 8]]])

#### eye->identity

In [5]:
d = np.eye(3)
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
arr1 = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

In [7]:
arr2 = np.array([[7, 8, 9],
                 [1, 2, 3],
                [4, 5, 6],])

## multiply

In [8]:
np.multiply(arr1,arr2)

array([[ 7, 16, 27],
       [ 4, 10, 18],
       [28, 40, 54]])

In [9]:
np.dot(arr1,arr2)

array([[ 21,  27,  33],
       [ 57,  72,  87],
       [ 93, 117, 141]])

## Tarnspose

In [10]:
arr1.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

## INVERSE

In [11]:
np.linalg.inv(arr1)

array([[-4.50359963e+15,  9.00719925e+15, -4.50359963e+15],
       [ 9.00719925e+15, -1.80143985e+16,  9.00719925e+15],
       [-4.50359963e+15,  9.00719925e+15, -4.50359963e+15]])

# PANDAS

In [15]:
data = [[1,"Ayush",20],
       [2,"Mridul",21],
       [3,"rajan",19]]
column = ["id","name","age"]

In [16]:
df = pd.DataFrame(data=data,columns=column)
df

id    name  age
0   1   Ayush   20
1   2  Mridul   21
2   3   rajan   19

In [19]:
data = {"name":["Ayush","Rajan","Mridul"],
             "id":[1,2,3],
             "age":[19,20,21]
}

In [20]:
df = pd.DataFrame(data)
df.head()

name  id  age
0   Ayush   1   19
1   Rajan   2   20
2  Mridul   3   21

# Index

In [26]:
data = {"name":["Ayush","Rajan","Mridul"],
             "id":[1,2,3],
             "age":[19,20,21]
}
df = pd.DataFrame(data,index=['a','b','c'])

In [27]:
df

name  id  age
a   Ayush   1   19
b   Rajan   2   20
c  Mridul   3   21

In [50]:
df = pd.read_csv('C:\\Users\\ayush\\dataset\\batter.csv')
df

batter  runs        avg  strike_rate
0           V Kohli  6634  36.251366   125.977972
1          S Dhawan  6244  34.882682   122.840842
2         DA Warner  5883  41.429577   136.401577
3         RG Sharma  5881  30.314433   126.964594
4          SK Raina  5536  32.374269   132.535312
..              ...   ...        ...          ...
600         C Nanda     0   0.000000     0.000000
601      Akash Deep     0   0.000000     0.000000
602         S Ladda     0   0.000000     0.000000
603  V Pratap Singh     0   0.000000     0.000000
604    S Lamichhane     0   0.000000     0.000000

[605 rows x 4 columns]

In [31]:
df.describe()

runs         avg  strike_rate
count   605.000000  572.000000   605.000000
mean    464.428099   15.912037   100.663928
std     985.272855   10.487649    39.956350
min       0.000000    0.000000     0.000000
25%      15.000000    7.729167    78.750000
50%      73.000000   14.421717   107.266436
75%     326.000000   23.041667   125.000000
max    6634.000000   55.666667   400.000000

In [32]:
df["new"] = df["avg"].mean() 

In [51]:
data = {
    'Name' : ['Aryan','Ayush','Ram','Laxman','Sita'],
    'Age' : [21, 20, 26, 19, 24],
    'Gender' : ['M', 'M', 'M', 'M', 'F']
}

In [52]:
df = pd.DataFrame(data)

In [53]:

df.head()

Name  Age Gender
0   Aryan   21      M
1   Ayush   20      M
2     Ram   26      M
3  Laxman   19      M
4    Sita   24      F

In [55]:
new_df = df[df["Age"]<24]
new_df

Name  Age Gender
0   Aryan   21      M
1   Ayush   20      M
3  Laxman   19      M

In [57]:
df.describe()

Age
count   5.000000
mean   22.000000
std     2.915476
min    19.000000
25%    20.000000
50%    21.000000
75%    24.000000
max    26.000000

In [61]:
df['Age_Group'] = df['Age'].apply(lambda age: 'Young' if age <=21 else 'Old')

In [60]:
df

Name  Age Gender Age_Group
0   Aryan   21      M     Young
1   Ayush   20      M     Young
2     Ram   26      M       Old
3  Laxman   19      M     Young
4    Sita   24      F       Old

In [63]:
gender = df.groupby('Gender')['Age'].mean()
gender

Gender
F    24.0
M    21.5
Name: Age, dtype: float64

In [71]:
df['Gender'].value_counts()

Gender
M    4
F    1
Name: count, dtype: int64

In [83]:
data = {
    'Name': ["Alice", "Bob", 'Charlie', 'David', 'Emily'],
    'Age' : [25, 38, None, 28, 24],
    'Gender': ['f', 'm', 'm', 'm', 'f'],
    'Math_Score': [85, 92, 78, 88, 76],
    'Science_Score': [90, None, 85, 92, 88],
    'Passed_Exam': ['Yes', 'Yes', 'NO', 'Yes', 'No']
}

In [84]:
df = pd.DataFrame(data)
df

Name   Age Gender  Math_Score  Science_Score Passed_Exam
0    Alice  25.0      f          85           90.0         Yes
1      Bob  38.0      m          92            NaN         Yes
2  Charlie   NaN      m          78           85.0          NO
3    David  28.0      m          88           92.0         Yes
4    Emily  24.0      f          76           88.0          No

In [85]:
df['Age'].fillna(df['Age'].mean(), inplace = True)
df

Name    Age Gender  Math_Score  Science_Score Passed_Exam
0    Alice  25.00      f          85           90.0         Yes
1      Bob  38.00      m          92            NaN         Yes
2  Charlie  28.75      m          78           85.0          NO
3    David  28.00      m          88           92.0         Yes
4    Emily  24.00      f          76           88.0          No

In [87]:
df.dropna(subset=['Science_Score'], inplace = True)
df

Name    Age Gender  Math_Score  Science_Score Passed_Exam
0    Alice  25.00      f          85           90.0         Yes
2  Charlie  28.75      m          78           85.0          NO
3    David  28.00      m          88           92.0         Yes
4    Emily  24.00      f          76           88.0          No

In [88]:
label_encoder = LabelEncoder()
df['Gender'] = label_encoder.fit_transform(df['Gender'])
df['Passed_Exam'] = label_encoder.fit_transform(df['Passed_Exam'])
df

Name    Age  Gender  Math_Score  Science_Score  Passed_Exam
0    Alice  25.00       0          85           90.0            2
2  Charlie  28.75       1          78           85.0            0
3    David  28.00       1          88           92.0            2
4    Emily  24.00       0          76           88.0            1